#  -- POD --
#   - Group of one or more containers with shared storage and network and a specification for how to run the containers.
#   - It is the most basic unit of deployment in k8s.
 #  - Pods are not visible outside the k8s cluster. Meaning, I cannot access a webapp in a pod from a browser (they need a service for that)

apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-arm64


# steps to create the pod
# 1 - type the command: kubectl apply -f pod.yaml
# 2 - type the command: kubectl get pod
