# it is a common practice to call a file with multiple resources (deployments, services, pods) as `workloads` - ref https://kubernetes.io/docs/concepts/workloads/

apiVersion: apps/v1
kind: Deployment
metadata: # recommended to have a name
  name: queue
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: queue # deployment will control any pod that matches this label
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1-arm64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1-arm64
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release1-arm64
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
                   